### ISSUE TITLE
Each cohort member must add his/her bio info to classlist.json

### ISSUE THREAD

**Issue by estorms** [nss-day-cohort-15/nss-day-cohort-15.github.io#23]
### Feature Description
Every member of the cohort must add a ~200 word bio to the `classlist.json` file. Please check your name off below once the PR on your bio has been approved. **Deadline: Friday, 12/9.**

###Required Participants
- [x] Matt Kraatz
- [x] Matt Hamil
- [x] Garrett Vangilder
- [x] Liz Sanger
- [x] Casey Reed
- [x] Dayne Wright
- [x] Debbie Bourne
- [x] Delaine Wendling
- [x] Jamie Duke
- [x] Edgar Barajas
- [x] Anulfo Ordaz
- [x] Elliott Williams
- [x] Fletcher Watson
- [x] Meg Ducharme
- [x] Tom Shavor
- [x] Zack Repass
- [x] Yonathon Molla
- [x] Jacob Keen
- [x] Jammy Laird
- [x] Chris Smalley
- [x] David Yunker
- [x] Grant Regnier

### Recommended Actions
N/A

### Related Issues/PRs
N/A

**Comment by matthamil** [comment]
Commenting to bring this to everyone's attention as well:

When you include a link to your LinkedIn and personal website/portfolio page, prefix the URLs with **http://** or **https://**. Otherwise, when the links are loaded on the page, they will redirect to `http://cohortwebsite.com/yourlink` which isn't the intended behavior.

**Comment by matthamil** [comment]
Thanks y'all :tada:

**Comment by daynewright** [comment]
👍   GO TEAM!
